CREATE TABLE ATLETA(
    CODIGO_DE_IDENTIFICACAO NUMBER NOT NULL,
    NOME VARCHAR2(40) NOT NULL,
    NUMERO_DO_PASSAPORTE NUMBER NOT NULL UNIQUE,
    SEXO CHAR NOT NULL,
    CHECK(SEXO IN ('M','F')),
    DATA_DE_NASCIMENTO DATE NOT NULL,
    ALTURA DECIMAL(3,2) NOT NULL,
    PESO NUMBER NOT NULL,
    CHECK(ALTURA > 0),
    CHECK(PESO > 0),
    PRIMARY KEY (CODIGO_DE_IDENTIFICACAO)
);

CREATE TABLE ARBITRO(
    CODIGO_DE_IDENTIFICACAO NUMBER NOT NULL,
    NOME VARCHAR2(40) NOT NULL,
    NUMERO_DO_PASSAPORTE NUMBER NOT NULL UNIQUE,
    SEXO CHAR CHECK(SEXO IN ('M','F')),
    DATA_DE_NASCIMENTO DATE,
    PRIMARY KEY (CODIGO_DE_IDENTIFICACAO)
);

CREATE TABLE PAIS(
    NOME VARCHAR2(40) NOT NULL,
    HINO VARCHAR2(4000),
    CONTINENTE VARCHAR2(30),
    CHECK(CONTINENTE IN ('América do Norte', 'América Central', 'América do Sul', 'Europa', '�?frica', '�?sia', 'Oceania')),
    BANDEIRA BLOB,
    PRIMARY KEY (NOME)
);

CREATE TABLE LOCAL(
    NOME VARCHAR2(40) NOT NULL,
    ENDERECO VARCHAR2(100) NOT NULL,
    CAPACIDADE NUMBER NOT NULL,
    PRIMARY KEY(NOME),
    CHECK(CAPACIDADE > 0)
);

CREATE TABLE ESPORTE(
    NOME VARCHAR2(40) NOT NULL,
    UNIDADE_DE_PONTUACAO VARCHAR2(30) NOT NULL,
    PRIMARY KEY (NOME)
);

CREATE TABLE MODALIDADE(
    ESPORTE VARCHAR2(40) NOT NULL,
    NOME VARCHAR2(20) NOT NULL,
    CATEGORIA VARCHAR2(20) NOT NULL,
    NUMERO_DE_ATLETAS_EQUIPE NUMBER NOT NULL,
    CRITERIO_DE_VITORIA VARCHAR(10) NOT NULL,
    CHECK(CRITERIO_DE_VITORIA IN ('MAIOR', 'MENOR')),
    TOTAL_DE_FASES NUMBER,
    MEDALHA_OURO NUMBER,
    MEDALHA_PRATA NUMBER,
    MEDALHA_BRONZE NUMBER,
    PRIMARY KEY(NOME,CATEGORIA,ESPORTE),
    CONSTRAINT FK_MODALIDADE FOREIGN KEY (ESPORTE) 
        REFERENCES  ESPORTE(NOME) ON DELETE CASCADE
);

CREATE TABLE COMPETICAO(
    NUMERO_DE_IDENTIFICACAO NUMBER NOT NULL,
    DIA_E_HORA DATE NOT NULL,
    NUMERO_DE_FASE NUMBER NOT NULL,
    CHECK(NUMERO_DE_FASE > 0),
    OBSERVACOES_GERAIS VARCHAR2(1000),
    LOCAL VARCHAR2(40) NOT NULL,
    PRIMARY KEY (NUMERO_DE_IDENTIFICACAO),
    CONSTRAINT FK_COMPETICAO_LOCAL FOREIGN KEY (LOCAL) 
        REFERENCES LOCAL(NOME) ON DELETE SET NULL
);

CREATE TABLE EQUIPE(
    NUMERO_DE_EQUIPE NUMBER NOT NULL,
    NOME_MODALIDADE VARCHAR2(20) NOT NULL,
    CATEGORIA_MODALIDADE VARCHAR2(20) NOT NULL,
    ESPORTE VARCHAR2(40) NOT NULL,
    REPRESENTA_PAIS VARCHAR2(40) NOT NULL,
    PRIMARY KEY (NUMERO_DE_EQUIPE),
    CONSTRAINT FK_EQUIPE_MODALIDADE_N FOREIGN KEY (NOME_MODALIDADE,CATEGORIA_MODALIDADE,ESPORTE)
        REFERENCES  MODALIDADE(NOME,CATEGORIA,ESPORTE) ON DELETE CASCADE,
    CONSTRAINT FK_EQUIPE_PAIS FOREIGN KEY (REPRESENTA_PAIS) 
        REFERENCES  PAIS(NOME) ON DELETE SET NULL
);

CREATE TABLE ATLETA_TEM_NACIONALIDADE(
    ATLETA NUMBER NOT NULL,
    PAIS VARCHAR2(40) NOT NULL,
    REPRESENTA_A_NACAO CHAR(1) NOT NULL,
    CHECK(REPRESENTA_A_NACAO IN ('0','1')),
    PRIMARY KEY(ATLETA,PAIS),
    CONSTRAINT FK_ATN_ATLETA FOREIGN KEY (ATLETA) 
        REFERENCES ATLETA(CODIGO_DE_IDENTIFICACAO) ON DELETE SET NULL,
    CONSTRAINT FK_ATN_PAIS FOREIGN KEY (PAIS) 
        REFERENCES  PAIS(NOME) ON DELETE SET NULL
);

CREATE TABLE ARBITRO_TEM_NACIONALIDADE(
    ARBITRO NUMBER NOT NULL,
    PAIS VARCHAR2(40) NOT NULL,
    REPRESENTA_A_NACAO CHAR(1),
    CHECK(REPRESENTA_A_NACAO IN ('0','1')),
    PRIMARY KEY(ARBITRO,PAIS),
    CONSTRAINT FK_ARBT_TN_ARBITRO FOREIGN KEY (ARBITRO) 
        REFERENCES ARBITRO(CODIGO_DE_IDENTIFICACAO) ON DELETE SET NULL,
    CONSTRAINT FK_ARB_TN_PAIS FOREIGN KEY (PAIS) 
        REFERENCES  PAIS(NOME) ON DELETE SET NULL
);

CREATE TABLE LEVA_A(
    COMPETICAOA NUMBER NOT NULL,
    COMPETICAOB NUMBER NOT NULL,
    POSICAO_NA_CLASSIFICACAO NUMBER,
    VENCEDOR CHAR(1),
	  CHECK(VENCEDOR IN ('0','1')),
    PRIMARY KEY(COMPETICAOA,COMPETICAOB),
    CONSTRAINT FK_LEVAA_COMPETICAOA FOREIGN KEY (COMPETICAOA) 
        REFERENCES  COMPETICAO(NUMERO_DE_IDENTIFICACAO) ON DELETE CASCADE,
    CONSTRAINT FK_LEVAA_COMPETICAOB FOREIGN KEY (COMPETICAOB) 
        REFERENCES  COMPETICAO(NUMERO_DE_IDENTIFICACAO) ON DELETE CASCADE
);

CREATE TABLE ARBITRA(
    COMPETICAO NUMBER NOT NULL,
    ARBITRO NUMBER NOT NULL,
    PAPEL VARCHAR2(30),
    PRIMARY KEY (COMPETICAO,ARBITRO),
    CONSTRAINT FK_ARBITRA_COMPETICAO FOREIGN KEY (COMPETICAO) 
        REFERENCES  COMPETICAO(NUMERO_DE_IDENTIFICACAO) ON DELETE CASCADE,

    CONSTRAINT FK_ARBITRA_ARBITRO FOREIGN KEY (ARBITRO) 
        REFERENCES ARBITRO(CODIGO_DE_IDENTIFICACAO) ON DELETE CASCADE
);

CREATE TABLE ESTA_HABILITADO_PARA_ARBITRAR(
    ESPORTE VARCHAR2(40) NOT NULL,
    ARBITRO NUMBER NOT NULL,
    PRIMARY KEY(ESPORTE,ARBITRO),
    CONSTRAINT FK_EHPA_ESPORTE FOREIGN KEY (ESPORTE) 
        REFERENCES  ESPORTE(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_EHPA_ARBITRO FOREIGN KEY (ARBITRO) 
        REFERENCES ARBITRO(CODIGO_DE_IDENTIFICACAO) ON DELETE CASCADE
);

CREATE TABLE JOGA(
    EQUIPE NUMBER NOT NULL,
    COMPETICAO NUMBER NOT NULL,
    RESULTADO NUMBER NOT NULL,
    VENCEDOR CHAR NOT NULL,
    CHECK(VENCEDOR IN ('V','P','E')),
    PRIMARY KEY(EQUIPE,COMPETICAO),
    CONSTRAINT FK_JOGA_EQUIPE FOREIGN KEY (EQUIPE) 
        REFERENCES  EQUIPE(NUMERO_DE_EQUIPE) ON DELETE CASCADE,
    CONSTRAINT FK_JOGA_COMPETICAO FOREIGN KEY (COMPETICAO) 
        REFERENCES  COMPETICAO(NUMERO_DE_IDENTIFICACAO) ON DELETE CASCADE
);

CREATE TABLE PARTICIPA(
    ATLETA NUMBER NOT NULL,
    EQUIPE NUMBER NOT NULL,
    PRIMARY KEY(ATLETA,EQUIPE),
    CONSTRAINT FK_PARTICIPA_LOCAL FOREIGN KEY (ATLETA) 
        REFERENCES  ATLETA(CODIGO_DE_IDENTIFICACAO) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPA_EQUIPE FOREIGN KEY (EQUIPE) 
        REFERENCES  EQUIPE(NUMERO_DE_EQUIPE) ON DELETE CASCADE
);

CREATE TABLE SUPORTA(
    LOCAL VARCHAR2(40) NOT NULL,
    ESPORTE VARCHAR2(40) NOT NULL,
    PRIMARY KEY(LOCAL,ESPORTE),
    CONSTRAINT FK_SUPORTA_LOCAL FOREIGN KEY (LOCAL) 
        REFERENCES  LOCAL(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_SUPORTA_ESPORTE FOREIGN KEY (ESPORTE) 
        REFERENCES  ESPORTE(NOME) ON DELETE CASCADE
);

/*Cascades:
APAGA MODALIDADE: CASCADE EQUIPE
APAGA ESPORTE: CASCADE MODALIDADE, CASCADE EQUIPE, CASCADE SUPORTA, CASCADE ESTA_HABILITADO_PARA_ARBITRAR
APAGA EQUIPE: CASCADE PARTICIPA, CASCADE JOGA
APAGA ATLETA: CASCADE PARTICIPA
APAGA LOCAL: CASCADE SUPORTA
APAGA COMPETICAO: CASCADE JOGA, CASCADE ARBITRA, CASCADE LEVAA
APAGA ARBITRO: CASCADE ESTA_HABILITADO_PARA_ARBITRAR, CASCADE ARBITRA
Problemas encontrados:
Modificações feitas:
O tamanho especificado para hino não é suportado: definido como varchar2(4000)
Como DATE já armazena as horas, a hora em competição foi fundida ao dia.
Como não existe o tipo BOOLEAN no ORACLE, ele foi substituido por um char(1) de valor 0 ou 1
definir pais que representa em atleta,
RESULTADO.COMPETICAO-> DEFINIDO COMO NUMBER
CRITERIO_DE_VITORIA.MODALIDADE-> DEFINIDO COMO VARCHAR2 MAIOR OU MENOR
*/
