SELECT A.CODIGO_DE_IDENTIFICACAO, A.NOME, A.NUMERO_DO_PASSAPORTE, A.SEXO, COUNT(*) AS NRO_TOTAL_JOGOS FROM JOGA J JOIN PARTICIPA P ON P.EQUIPE = J.EQUIPE JOIN ATLETA A ON A.CODIGO_DE_IDENTIFICACAO = P.ATLETA
GROUP BY A.CODIGO_DE_IDENTIFICACAO, A.NOME, A.NUMERO_DO_PASSAPORTE, A.SEXO
HAVING COUNT(*) >= 3;